### ISSUE TITLE
Error in Seismic Noise Tomography mseed assignment

### ISSUE THREAD

**Issue by boland1992** [bgoutorbe/seismic-noise-tomography#15]
Hi there, my name's Benjamin Boland and I'm currently working on incorporating seismic noise tomography into the system in Gippsland, south eastern Victoria in Australia. I'm currently working on my masters project in SMT and would very much like to incorporate this code into this project. 

I'm currently getting the following errors: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 586, in runfile
    execfile(filename, namespace)
  File "/home/boland/Documents/seismic-noise-tomography-master/crosscorrelation.py", line 458, in <module>
    xc.export(outprefix=OUTFILESPATH, stations=stations, verbose=True)
  File "pysismo/pscrosscorr.py", line 1839, in export
    self._to_ascii(outprefix, verbose=verbose)
  File "pysismo/pscrosscorr.py", line 2031, in _to_ascii
    data = zip(self._get_timearray(), *[self[s1][s2].dataarray for s1, s2 in pairs])
  File "pysismo/pscrosscorr.py", line 2135, in _get_timearray
    s1, s2 = pairs[0]
IndexError: list index out of range

Try as I might, I'm unable to get the cross-correlations to export into the correct format, as the time-array  pairs() function isn't correctly assigning values in my case. 

Any suggestions on how to fix this would be greatly appreciated.

Please either comment back or my email is boland1992@gmail.com, thank you so much for you time and help and if I could get this thing running for our systems that would be amazing!

Your code looks nigh on perfect for my needs here, it's just something wrong that I'm doing on my end I'm sure of it. 

Cheers and have a great day!
Benjamin Boland

**Comment by bgoutorbe** [comment]
Hi Benjamin,
it seems that you do not have any cross-correlation actually calculated.
Check your object 'xc'. If it contains cross-correlations you should get results such as these:

>>> xc
(AttribDict)<Collection of cross-correlation between 477 pairs>
>>> xc.pairs()
[('NUPB', 'RCBR'), ('NUPB', 'PTGA'), ('NUPB', 'POPB'), ...]

cheers
Bruno

**Comment by boland1992** [comment]
Our stations are independent of IRIS at the present time. This means we attempting to set up the XML files ourselves. We believe that incorrect formatting of this file has resulted in the empty list of xc.pairs() in your program. Would you be able to send us an example of a dummy functioning data structure/XML file for comparison?

When running the overall program we have: 

scanning stations in dir: /home/boland/Documents/AGOS_DATA/NETWORKS
Found 2 stations
Inserting coordinates to stations from inventories
[<Station AG.EHZ.HOLS>, <Station AG.EHZ.CLIF>]


Processing data of day  2014-01-01
AG.CLIF [54% fill: skipped] | AG.HOLS [no other station: skipped] 
Stacking cross-correlations


Processing data of day  2014-01-02
AG.CLIF [no resp: skipped] | AG.HOLS [no other station: skipped] 
Stacking cross-correlations


Processing data of day  2014-01-03
AG.CLIF [no resp: skipped] | AG.HOLS [no other station: skipped] 
Stacking cross-correlations


Processing data of day  2014-01-04
AG.CLIF [no resp: skipped] | AG.HOLS [no other station: skipped] 
Stacking cross-correlations


Processing data of day  2014-01-05
AG.CLIF [no resp: skipped] | AG.HOLS [no other station: skipped] 
Stacking cross-correlations

then in the exportation phase we get the above error. 

Thanks so much for your help Bruno. We greatly appreciate it. 

Cheers,
Benjamin

**Comment by bgoutorbe** [comment]
The problem is not an incorrect formatting, the problem is that no XML file is found at all. Make sure that your stationxml files reside in STATIONXML_DIR, have the extension *.xml and that USE_STATIONXML = true.

Let me know if the program works!
